AWSTemplateFormatVersion: '2010-09-09'
Description: 'Kelifax Lambda Function with DynamoDB and CloudWatch access'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment (dev, prod)
    AllowedValues:
      - dev
      - prod
      
  FunctionPrefix:
    Type: String
    Default: kelifax
    Description: Prefix for the Lambda function name
    
  DeploymentBucket:
    Type: String
    Default: cf-kelifax-deployment-bucket
    Description: S3 bucket containing the Lambda function code zip files
    
  S3KeyPrefix:
    Type: String
    Default: lambda-zip-dev
    Description: S3 key prefix for Lambda function code zip files
  
  S3ZipFile:
    Type: String
    Default: lambda-function.zip
    Description: Name of the Lambda zip file in S3
  
  ApiKey:
    Type: String
    Description: API Key ID for Gateway (reference an existing API Key ID from the console)
    Default: h5tbv3v5g0

Mappings:
  EnvironmentToTableName:
    prod:
      TableName: kelifax-resources-prod
    dev:
      TableName: kelifax-SubmittedResources-Dev



Resources:
  # Lambda Function
  KelilaxFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 
        Fn::Sub: "${FunctionPrefix}-${Environment}-function"
      Handler: app.lambda_function.lambda_handler
      Runtime: python3.12
      Code:
        S3Bucket: 
          Ref: DeploymentBucket
        S3Key: 
          Fn::Sub: "${S3KeyPrefix}/${S3ZipFile}"
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: 
            Ref: Environment
          DYNAMODB_TABLE: 
            Fn::FindInMap: 
              - EnvironmentToTableName
              - Ref: Environment
              - TableName
      Role: 
        Fn::GetAtt: 
          - LambdaExecutionRole
          - Arn

  # IAM Role for Lambda Execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:GetItem'
                  - 'dynamodb:PutItem'
                  - 'dynamodb:UpdateItem'
                  - 'dynamodb:DeleteItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                Resource:
                  - Fn::Sub:
                      - 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}'
                      - TableName:
                          Fn::FindInMap:
                            - EnvironmentToTableName
                            - Ref: Environment
                            - TableName
                  - Fn::Sub:
                      - 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${TableName}/index/*'
                      - TableName:
                          Fn::FindInMap:
                            - EnvironmentToTableName
                            - Ref: Environment
                            - TableName
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:GetParametersByPath'
                Resource:
                  - Fn::Sub: 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${FunctionPrefix}/${Environment}/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - !Sub 'arn:aws:s3:::kelifax-resources/${Environment}/uploads/temp/*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - !Sub 'arn:aws:s3:::kelifax-resources/${Environment}/logos/approved/*'
                  - !Sub 'arn:aws:s3:::kelifax-resources/${Environment}/logos/pending/*'

  # API Gateway Resources
  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${FunctionPrefix}-${Environment}-api"
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayResourceAdminAuth:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt [ApiGatewayRestApi, RootResourceId]
      PathPart: "admin-auth"

  ApiGatewayResourceResources:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt [ApiGatewayRestApi, RootResourceId]
      PathPart: "resources"

  ApiGatewayResourceGetResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt [ApiGatewayRestApi, RootResourceId]
      PathPart: "get-resource"

  ApiGatewayResourceSubmitResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt [ApiGatewayRestApi, RootResourceId]
      PathPart: "submit-resource"

  ApiGatewayResourceUploadLogo:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt [ApiGatewayRestApi, RootResourceId]
      PathPart: "upload-logo"

  # OPTIONS Methods for CORS
  ApiGatewayMethodAdminAuthOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceAdminAuth
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayMethodResourcesOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceResources
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayMethodGetResourceOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceGetResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayMethodSubmitResourceOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceSubmitResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiGatewayMethodUploadLogoOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceUploadLogo
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: "{}"
        RequestTemplates:
          application/json: "{ \"statusCode\": 200 }"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # API Methods
  ApiGatewayMethodAdminAuthPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceAdminAuth
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodResourcesDelete:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceResources
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodResourcesGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceResources
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodResourcesPatch:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceResources
      HttpMethod: PATCH
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodResourcesPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceResources
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodGetResourcePost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceGetResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodSubmitResourcePost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceSubmitResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  ApiGatewayMethodUploadLogoPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourceUploadLogo
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${KelilaxFunction.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200

  # Lambda Permissions for API Gateway
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref KelilaxFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*"

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: !Ref Environment
    DependsOn:
      - ApiGatewayMethodAdminAuthPost
      - ApiGatewayMethodAdminAuthOptions
      - ApiGatewayMethodResourcesGet
      - ApiGatewayMethodResourcesPost
      - ApiGatewayMethodResourcesPatch
      - ApiGatewayMethodResourcesDelete
      - ApiGatewayMethodResourcesOptions
      - ApiGatewayMethodGetResourcePost
      - ApiGatewayMethodGetResourceOptions
      - ApiGatewayMethodSubmitResourcePost
      - ApiGatewayMethodSubmitResourceOptions
      - ApiGatewayMethodUploadLogoPost
      - ApiGatewayMethodUploadLogoOptions

  # Usage Plan
  ApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${FunctionPrefix}-${Environment}-usage-plan"
      ApiStages:
        - ApiId: !Ref ApiGatewayRestApi
          Stage: !Ref Environment
      Description: !Sub "Usage plan for ${FunctionPrefix}-${Environment}"
    DependsOn:
      - ApiGatewayDeployment

  # Usage Plan Key
  ApiGatewayUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: "API_KEY"
      UsagePlanId: !Ref ApiGatewayUsagePlan

Outputs:
  FunctionArn:
    Description: "ARN of the Kelifax Lambda function"
    Value:
      Fn::GetAtt:
        - KelilaxFunction
        - Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FunctionArn"
  
  FunctionName:
    Description: "Name of the Kelifax Lambda function"
    Value:
      Ref: KelilaxFunction
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-FunctionName"
      
  DynamoDBTableName:
    Description: "Name of the DynamoDB table used by this function"
    Value:
      Fn::FindInMap:
        - EnvironmentToTableName
        - Ref: Environment
        - TableName
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-DynamoDBTableName"
      
  RoleArn:
    Description: "ARN of the IAM role used by the Lambda function"
    Value:
      Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-RoleArn"

  ApiGatewayUrl:
    Description: "URL of the API Gateway"
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayUrl"
      
  ApiGatewayStage:
    Description: "Name of the API Gateway stage"
    Value: !Ref Environment
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayStage"
