AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Kelifax Lambda Function with DynamoDB and CloudWatch access'

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment (dev, prod)
    AllowedValues:
      - dev
      - prod
      
  FunctionPrefix:
    Type: String
    Default: kelifax
    Description: Prefix for the Lambda function name

Mappings:
  EnvironmentToTableName:
    prod:
      TableName: kelifax-resources-prod
    dev:
      TableName: kelifax-SubmittedResources-Dev

Resources:
  # Lambda Function
  KelilaxFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${FunctionPrefix}-${Environment}-function"
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: ../../../lambda/app/
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          DYNAMODB_TABLE: !FindInMap [EnvironmentToTableName, !Ref Environment, TableName]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !FindInMap [EnvironmentToTableName, !Ref Environment, TableName]
        - CloudWatchLogsFullAccess

Outputs:
  FunctionArn:
    Description: "ARN of the Kelifax Lambda function"
    Value: !GetAtt KelilaxFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
  
  FunctionName:
    Description: "Name of the Kelifax Lambda function"
    Value: !Ref KelilaxFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"
      
  DynamoDBTableName:
    Description: "Name of the DynamoDB table used by this function"
    Value: !FindInMap [EnvironmentToTableName, !Ref Environment, TableName]
    Export:
      Name: !Sub "${AWS::StackName}-DynamoDBTableName"